services:
  database:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: directus
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  directus:
    image: directus/directus:latest
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "8055:8055"
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      DB_CLIENT: pg
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      PUBLIC_URL: http://localhost:8055
    volumes:
      - ./be/directus/uploads:/directus/uploads
      - ./be/directus/extensions:/directus/extensions

  backend:
    build:
      context: ./be/express
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - directus
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DIRECTUS_URL: http://directus:8055
      DIRECTUS_TOKEN: ${DIRECTUS_TOKEN}

  frontend:
    build:
      context: ./fe
      dockerfile: dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      PORT: 3000
      HOSTNAME: 0.0.0.0

volumes:
  postgres_data:
