// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const cliDatabaseUrl =
  // Preserve the backend's existing local-development convention first.
  process.env.DB_URL ||
  process.env.DIRECT_URL ||
  process.env.DATABASE_URL ||
  // `prisma generate` does not connect to the database, but Prisma still parses
  // the datasource config. Real database commands must set DB_URL/DIRECT_URL.
  "postgresql://postgres:postgres@localhost:5432/postgres";

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: cliDatabaseUrl,
  },
  migrations: {
    seed: "npx tsx prisma/seed.ts",
  },
});
